### ISSUE TITLE
Add a Remove-LineForward command

### ISSUE THREAD

**Issue by drowe13** [joshuanasiatka/CUCMPosh#1]
**Is your feature request related to a problem? Please describe.**
It is easy to use set-lineforward to forward a line, however there isn't an easy way to UNforward the line after 
**Describe the solution you'd like**
change set-lineforward to add-lineforward, and then create a remove-lineforward

**Describe alternatives you've considered**
Could add a flag for set-lineforward 1 for add a line forward, and set-lineforward 0 for removing a lineforward

**Comment by tealise** [comment]
Fixed with release v0.0.1
